package leet.simple;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class FindTheDifference {
    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        char c = findTheDifference(s, t);
        System.out.println(c);

    }
    public static char findTheDifference(String s, String t) {
        int input1 = 0;
        int input2 = 0;
        for(int i = 0 ; i < s.length() ; i++) {
            input1 += s.charAt(i);
        }
        for(int i = 0 ; i < t.length() ; i++) {
            input2 += t.charAt(i);
        }

        return (char)(input2 - input1);
    }
}

/*
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
 */